"""Offline tests for the conflict domain (no network)."""

import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

SRC = str(Path(__file__).resolve().parent.parent / "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from conflict import _lib  # noqa: E402
from conflict.handlers import conflict_handlers as ch  # noqa: E402


def test_metric_registry():
    keys = [m.key for m in _lib.METRICS]
    assert keys == ["events", "deaths", "civilian", "intensity", "actors"]
    assert _lib.BY_KEY["intensity"].fmt == "rate" if hasattr(_lib, "BY_KEY") else True
    assert all(m.fmt in ("count", "rate") for m in _lib.METRICS)


def test_dispatch_keys():
    assert set(ch._DISPATCH) == {
        "conflict.sources.DownloadUCDP",
        "conflict.maps.BuildConflictMap",
    }


def test_register_handlers():
    runner = MagicMock()
    ch.register_handlers(runner)
    assert runner.register_handler.call_count == 2


def test_aliases_are_strings():
    assert _lib.COUNTRY_ALIASES["DR Congo (Zaire)"] == "Dem. Rep. Congo"
    assert all(isinstance(k, str) and isinstance(v, str) for k, v in _lib.COUNTRY_ALIASES.items())


def test_render_html_from_synthetic_aggregate(monkeypatch, tmp_path):
    """Render path works end-to-end with a tiny synthetic aggregate + geometry,
    no network — verifies the dropdown, attribution, and intensity math."""
    os.environ["AFL_STORAGE"] = "local"
    os.environ["AFL_DATA_ROOT"] = str(tmp_path)
    agg = {"Ukraine": {"events": 100, "deaths": 5000, "civilian": 3, "actors": 4}}
    world = {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature", "properties": {"NAME": "Ukraine", "POP_EST": 40000000},
             "geometry": {"type": "Polygon", "coordinates": [[[0, 0], [0, 1], [1, 1], [0, 0]]]}},
            {"type": "Feature", "properties": {"NAME": "Sweden", "POP_EST": 10000000},
             "geometry": {"type": "Polygon", "coordinates": [[[2, 2], [2, 3], [3, 3], [2, 2]]]}},
        ],
    }
    monkeypatch.setattr(_lib, "download_ucdp_aggregate", lambda **k: (2024, agg))
    monkeypatch.setattr(_lib, "_world_geojson", lambda: world)
    res = _lib.build_conflict_map()
    assert res.year == 2024 and res.country_count == 1
    html = _lib.cstore.open_read(res.html_path).read()
    assert "Generated by Facetwork" in html and "view FFL" in html
    assert all(m.label in html for m in _lib.METRICS)
    # intensity = 5000 / 40,000,000 * 100k = 12.5
    assert '"m_intensity":12.5' in html.replace(" ", "")
